name: Deploy Docker image to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx (required for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build --tag yogendradots/pythonflaskapp:${{ github.sha }} .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: |
        docker push yogendradots/pythonflaskapp:${{ github.sha }}

    # Step 6: SSH into EC2 instance, pull the image, and run the container
    - name: SSH to EC2 instance and deploy Docker container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 13.40.56.224  # Your EC2 instance IP
        username: ubuntu     # Your EC2 username, change if needed
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # SSH private key secret
        script: |
          echo "Pulling Docker image from Docker Hub..."
          docker pull yogendradots/pythonflaskapp:${{ github.sha }}
          docker stop my_flask_app || true  # Stop the previous container if running
          docker rm my_flask_app || true    # Remove the previous container
          echo "Running Docker container..."
          docker run -d --name my_flask_app -p 5000:5000 yogendradots/pythonflaskapp:${{ github.sha }}

