name: Build, Push, and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main   # Trigger when pushing to the main branch

jobs:
  # Step 1: Build and push Docker image to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yogendradots/pythonflaskapp:${{ github.sha }} .
          docker push yogendradots/pythonflaskapp:${{ github.sha }}

  # Step 2: Deploy to EC2
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Docker container to EC2
        run: |
          # Variables
          EC2_USER=ubuntu   # EC2 username (adjust if using a different username)
          EC2_IP=13.40.56.224  # Your EC2 instance IP address
          IMAGE_TAG=yogendradots/pythonflaskapp:${{ github.sha }}

          # SSH into EC2 instance and pull the image
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_IP} << 'EOF'
            # Update the system and install Docker if not installed
            sudo apt-get update -y
            sudo apt-get install -y docker.io

            # Pull the latest Docker image from Docker Hub
            sudo docker pull $IMAGE_TAG

            # Run the Docker container
            sudo docker run -d -p 5000:5000 $IMAGE_TAG
          EOF

